language: ruby
rvm:
- 2.1

script:
  - bundle exec rubocop
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site # --check-favicon --check-html

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

notifications:
  slack: columbiaspace:HZMOaxVpuQwUOIcAXkAxECkp
