title: Columbia Space Initiative
email: columbiaspace@gmail.com # why...
description: > # this means to ignore newlines until "baseurl:"
  For the pursuit of knowledge in near-space, space, and beyond.
url: "http://columbiaspace.github.io"
baseurl: ""

# Build settings
port: 5000
highlighter: pygments
markdown: redcarpet
permalink: pretty
