title: Columbia Space Initiative
email: columbiaspace@gmail.com # why...
description: For the pursuit of knowledge in near-space, space, and beyond.
url: "http://columbiaspace.org"
baseurl: ""

# Build settings
port: 5000
highlighter: pygments
markdown: redcarpet
permalink: pretty
