title: Columbia Space Initiative
email: columbiaspace@gmail.com # why...
description: For the pursuit of knowledge in near-space, space, and beyond.
url: "https://columbiaspace.org"
baseurl: ""

# Build settings
highlighter: rouge
markdown: kramdown
permalink: pretty
exclude:
  - vendor

# Google Analytics
google_analytics: UA-78617707-1