title: Columbia Space Initiative
email: columbiaspace@gmail.com # why...
description: For the pursuit of knowledge in near-space, space, and beyond.
url: "https://columbiaspace.org"
baseurl: ""

# Build settings
highlighter: rouge
markdown: kramdown
permalink: pretty
exclude:
  - vendor

# Google Analytics
google_analytics: UA-78617707-1

# prose.io
prose:
  rooturl: '_posts'
  siteurl: 'https://columbiaspace.org'
  media: 'assets/media'
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - .gitignore
    - .travis.yml
    - 404.html
    - CNAME
    - Gemfile
    - _config.yml
    - calendar.html
    - contact.html
    - feed.xml
    - index.html
    # get members into a directory of their own
    # same goes for missions and pastmissions
    - news.html
